apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orders
  name: orders
spec:
  ports:
  - name: "http"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: orders
  type: NodePort
