apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/cat-424106/payments/production
          name: payments
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: NOTIFICATIONS_HOST
              value: "notifications"
            - name: NOTIFICATION_PORT
              value: "3000"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
            - name: STRIPE_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiVersion
            - name: PORT
              value: '3001'
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: gcr-json-key
